# Generated by Django 3.0.5 on 2020-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["created_at"], name="post_likes_created_c52989_idx"
            ),
        ),
    ]
