# Generated by Django 3.0.5 on 2020-04-13 08:19

from django.db import migrations, models
from django.db.models.functions import TruncDate


def fill_created_date_from_created_at(apps, schema_editor):
    PostLike = apps.get_model("social_network", "PostLike")
    PostLike.objects.update(created_date=TruncDate("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0002_auto_20200413_0645"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlike",
            name="created_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.RemoveIndex(
            model_name='postlike',
            name='post_likes_created_c52989_idx',
        ),
        migrations.RunPython(
            code=fill_created_date_from_created_at,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="postlike",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["created_date"], name="post_likes_created_b046e3_idx"
            ),
        ),
    ]
